# Generated by Django 6.0.6 on 2026-08-21 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Obligatorio si el método de pago es "Fiado". Opcional si aplica descuento de profesor.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento aplicado a esta venta (ej. profesores).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('FIADO', 'Fiado (a cuenta)')], max_length=10),
        ),
    ]
