# Generated by Django 6.0.6 on 2026-08-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_cliente_venta_descuento_pct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='descuento_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento de profesor aplicado a esta venta (solo sobre las líneas marcadas).', max_digits=5),
        ),
    ]
