# Generated by Django 6.0.6 on 2026-08-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_servicio',
            field=models.BooleanField(default=False, help_text='Actívalo para servicios (fotocopias, impresiones, etc.) sin control de stock y con precio variable en cada venta.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Para servicios, este es solo un precio sugerido: podrás cambiarlo en cada venta.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='No aplica para servicios.'),
        ),
    ]
