# Generated by Django 6.0.6 on 2026-08-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_es_servicio_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='aplica_descuento_profesor',
            field=models.BooleanField(default=False, help_text='Actívalo solo en los productos/servicios donde el descuento de profesor debe aplicar (ej. copias). El resto del carrito no se descuenta.', verbose_name='Aplica descuento de profesor'),
        ),
    ]
