# Generated by Django 6.0.6 on 2026-08-21 22:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('es_profesor', models.BooleanField(default=False, help_text='Si está activo, se le aplica el descuento configurado abajo en cada venta.')),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento a aplicar. Solo tiene efecto si "Es profesor" está activo.', max_digits=5, verbose_name='Descuento (%)')),
                ('permite_fiado', models.BooleanField(default=False, help_text='Si está activo, este cliente puede llevarse productos a cuenta (fiado).')),
                ('limite_fiado', models.DecimalField(decimal_places=2, default=0, help_text='Deuda máxima permitida antes de bloquear nuevas ventas fiadas. 0 = sin límite.', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AbonoFiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Abono a fiado',
                'verbose_name_plural': 'Abonos a fiado',
                'ordering': ['-fecha'],
            },
        ),
    ]
