# Generated by Django 6.0.6 on 2026-06-30 20:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activa', models.BooleanField(default=True, help_text='Desactívala si esa caja deja de usarse, sin borrar su historial.')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10)),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto_inicial', models.DecimalField(decimal_places=2, help_text='Efectivo con el que se abre la gaveta al inicio del turno.', max_digits=10)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_esperado_efectivo', models.DecimalField(blank=True, decimal_places=2, help_text='Calculado al cerrar: inicial + efectivo vendido + ingresos - retiros.', max_digits=10, null=True)),
                ('monto_esperado_tarjeta', models.DecimalField(blank=True, decimal_places=2, help_text='Total vendido por tarjeta (informativo, no se cuenta físico).', max_digits=10, null=True)),
                ('monto_contado', models.DecimalField(blank=True, decimal_places=2, help_text='Conteo físico que ingresa el cajero al cerrar.', max_digits=10, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, help_text='monto_contado - monto_esperado_efectivo. (+) sobrante, (-) faltante.', max_digits=10, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='caja.caja')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RETIRO', 'Retiro'), ('INGRESO', 'Ingreso / cambio de fondo')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='caja.turno')),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTO')), fields=('caja',), name='una_caja_un_turno_abierto'),
        ),
    ]
